package com.mystipixel.royalbank.gui;

public enum BankGuiAction {
    OPEN_DEPOSIT,
    OPEN_WITHDRAW,
    DEPOSIT_ALL,
    DEPOSIT_HALF,
    DEPOSIT_CUSTOM,
    WITHDRAW_ALL,
    WITHDRAW_HALF,
    WITHDRAW_TWENTY,
    WITHDRAW_CUSTOM,
    UPGRADE,
    CONFIRM_UPGRADE,
    CLAIM_INTEREST,
    RECENT_TRANSACTIONS,
    BACK_MAIN,
    CLOSE,
    NONE
}
